import Head from "next/head";
import style from "../styles/Style.module.css";

export default function Layout(props: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.children}
    </>
  );
}
